### ISSUE TITLE
Dotnet Client API 

### ISSUE THREAD

**Issue by Lexcess** [experianplc/experian-dotnet#1]
Hi @sanketdevrao and @weber-stephen (and anyone else who is interested). Looking at what currently  have in `ExperianPlc` it seems like a pattern of having a client library for each language is forming. Given that, it would be good to leave a space so that each BU's API's could be added (either by the BU themselves or the community at large). 

So this is my attempt at putting a stake in the ground as to how that would look, at least for DotNet. 

I took the Java API and converted it over to idiomatic C#. I took the opportunity to partition BIS services into their own namespace so that we could add in DataQuality services side-by-side. I wonder if you could take a quick look and see if the structure makes sense. 

We for example have Java source code for our services we could potentially contribute (via Pull Request) to the `experian-java` repository. 

Love to know your thoughts.

**Comment by weber-stephen** [comment]
@Lexcess sounds great! Haven't done C# for awhile, but would love to take a look. We are definitely designing each SDK to allow each part of Experian add their own code to enable customers to access as much of our data as possible. Thanks so much for messaging us!

**Comment by Lexcess** [comment]
Closing this discussion for now.
