### ISSUE TITLE
Unable to get any example code working using a UK test token. (This project seems to be US only).

### ISSUE THREAD

**Issue by mattu08** [experianplc/experian-dotnet#19]
Hi,

I have been trying to get an authentication using the sample code provided.

I have just realised this project is only for use with the US API.

For example

Within the ServiceClient class OAuthStagingUrl, OAuthProductionUrl and OAuthSandboxUrl are set to the US URL’s.

Also the whole project is set up for the US Experian API entry's .

Could we have a project created for the UK Experian API, As the project doesn’t state anywhere in its current state, it only works with the US Experian API.

Thanks,

Matt

**Comment by Lexcess** [comment]
I don't work at Experian anymore, but the code was setup with the knowledge the regions would appear at some point (DS was global only used via US and BIS was US only at the time). So all that needs to happen is for API Extensions to be updated to include regions. Likewise for the ServiceClient. Should be a pretty quick job. 

The original code actually had it in, but it was removed as it confused some people into thinking services were available in multi-regions when actually they were US only.

**Comment by mattu08** [comment]
Hi @Lexcess thanks for the informative reply, I think that clears things up. I'll close the issue.
